"""Add words to transcripts

Revision ID: dc3cc38d0f99
Revises: 29796fd1cc25
Create Date: 2026-06-30 17:39:58.791882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3cc38d0f99'
down_revision: Union[str, None] = '29796fd1cc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('words', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'words')
    # ### end Alembic commands ###
